### ISSUE TITLE
Inquiry about Computational Resources

### ISSUE THREAD

**Issue by kangmg** [mtzgroup/chemcloud-client#70]
Hello,

I'm planning a project that requires approximately 10,000 single point and gradient calculations, and I found Chemcloud that supports Terachem. This seems like a great fit for my needs, but I have some questions about the available computational resources:

- Are there paid plans available for users with large-scale computation needs?
- What's the maximum number of batched calculations that can be run simultaneously?
- Are there any limitations on computational resources (e.g., time limits, job rate restrictions)?

Thank you for your help!

**Comment by coltonbh** [comment]
Hi @kangmg. Currently you'd need to run your own BigChem/ChemCloud instances on your own hardware (or on the cloud)--the software is available open source but we are not running a paid service anywhere for other people to use.

In the future it's possible we run an open ChemCloud server that other can use (and pay for), but for now it is up to each research to run their own.

If you like the interface and user experience you may want to consider [qcop](https://github.com/coltonbh/qcop) which will structure and execute your calculations for you on a single node. If you have multiple nodes and want to use them collectively [BigChem](https://github.com/mtzgroup/bigchem) is the easiest way to do this and I can help you setup a cluster, if you'd like :)
